/*
 * HolidayAPI
 * My API work College Work
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * Post Car Details
 */
@Schema(description = "Post Car Details")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2018-11-20T18:36:01.976Z[GMT]")public class PostCarDetails {

  @SerializedName("mark")
  private String mark = null;

  @SerializedName("model")
  private String model = null;

  @SerializedName("govNumber")
  private String govNumber = null;

  @SerializedName("linkToChip")
  private String linkToChip = null;
  public PostCarDetails mark(String mark) {
    this.mark = mark;
    return this;
  }

  

  /**
  * Get mark
  * @return mark
  **/
  @Schema(description = "")
  public String getMark() {
    return mark;
  }
  public void setMark(String mark) {
    this.mark = mark;
  }
  public PostCarDetails model(String model) {
    this.model = model;
    return this;
  }

  

  /**
  * Get model
  * @return model
  **/
  @Schema(description = "")
  public String getModel() {
    return model;
  }
  public void setModel(String model) {
    this.model = model;
  }
  public PostCarDetails govNumber(String govNumber) {
    this.govNumber = govNumber;
    return this;
  }

  

  /**
  * Get govNumber
  * @return govNumber
  **/
  @Schema(description = "")
  public String getGovNumber() {
    return govNumber;
  }
  public void setGovNumber(String govNumber) {
    this.govNumber = govNumber;
  }
  public PostCarDetails linkToChip(String linkToChip) {
    this.linkToChip = linkToChip;
    return this;
  }

  

  /**
  * Get linkToChip
  * @return linkToChip
  **/
  @Schema(description = "")
  public String getLinkToChip() {
    return linkToChip;
  }
  public void setLinkToChip(String linkToChip) {
    this.linkToChip = linkToChip;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostCarDetails postCarDetails = (PostCarDetails) o;
    return Objects.equals(this.mark, postCarDetails.mark) &&
        Objects.equals(this.model, postCarDetails.model) &&
        Objects.equals(this.govNumber, postCarDetails.govNumber) &&
        Objects.equals(this.linkToChip, postCarDetails.linkToChip);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(mark, model, govNumber, linkToChip);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostCarDetails {\n");
    
    sb.append("    mark: ").append(toIndentedString(mark)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    govNumber: ").append(toIndentedString(govNumber)).append("\n");
    sb.append("    linkToChip: ").append(toIndentedString(linkToChip)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
