/*
 * HolidayAPI
 * My API work College Work
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * Post Coming Details
 */
@Schema(description = "Post Coming Details")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2018-11-20T18:36:01.976Z[GMT]")public class PostComingDetails {

  @SerializedName("comments")
  private String comments = null;

  @SerializedName("Date")
  private OffsetDateTime date = null;

  @SerializedName("total")
  private Float total = null;

  @SerializedName("idStatement")
  private Integer idStatement = null;
  public PostComingDetails comments(String comments) {
    this.comments = comments;
    return this;
  }

  

  /**
  * Get comments
  * @return comments
  **/
  @Schema(description = "")
  public String getComments() {
    return comments;
  }
  public void setComments(String comments) {
    this.comments = comments;
  }
  public PostComingDetails date(OffsetDateTime date) {
    this.date = date;
    return this;
  }

  

  /**
  * Get date
  * @return date
  **/
  @Schema(description = "")
  public OffsetDateTime getDate() {
    return date;
  }
  public void setDate(OffsetDateTime date) {
    this.date = date;
  }
  public PostComingDetails total(Float total) {
    this.total = total;
    return this;
  }

  

  /**
  * Get total
  * @return total
  **/
  @Schema(description = "")
  public Float getTotal() {
    return total;
  }
  public void setTotal(Float total) {
    this.total = total;
  }
  public PostComingDetails idStatement(Integer idStatement) {
    this.idStatement = idStatement;
    return this;
  }

  

  /**
  * Get idStatement
  * @return idStatement
  **/
  @Schema(description = "")
  public Integer getIdStatement() {
    return idStatement;
  }
  public void setIdStatement(Integer idStatement) {
    this.idStatement = idStatement;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostComingDetails postComingDetails = (PostComingDetails) o;
    return Objects.equals(this.comments, postComingDetails.comments) &&
        Objects.equals(this.date, postComingDetails.date) &&
        Objects.equals(this.total, postComingDetails.total) &&
        Objects.equals(this.idStatement, postComingDetails.idStatement);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(comments, date, total, idStatement);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostComingDetails {\n");
    
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    idStatement: ").append(toIndentedString(idStatement)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
