/*
 * HolidayAPI
 * My API work College Work
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * PostOrderFromSiteDetails
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2018-11-20T18:36:01.976Z[GMT]")public class PostOrderFromSiteDetails {

  @SerializedName("date")
  private OffsetDateTime date = null;

  @SerializedName("city")
  private String city = null;

  @SerializedName("place")
  private String place = null;

  @SerializedName("timeStart")
  private OffsetDateTime timeStart = null;

  @SerializedName("timeEnd")
  private OffsetDateTime timeEnd = null;

  @SerializedName("phone")
  private String phone = null;

  @SerializedName("mailAddress")
  private String mailAddress = null;

  @SerializedName("attractions")
  private String attractions = null;

  @SerializedName("comments")
  private String comments = null;
  public PostOrderFromSiteDetails date(OffsetDateTime date) {
    this.date = date;
    return this;
  }

  

  /**
  * Get date
  * @return date
  **/
  @Schema(description = "")
  public OffsetDateTime getDate() {
    return date;
  }
  public void setDate(OffsetDateTime date) {
    this.date = date;
  }
  public PostOrderFromSiteDetails city(String city) {
    this.city = city;
    return this;
  }

  

  /**
  * Get city
  * @return city
  **/
  @Schema(description = "")
  public String getCity() {
    return city;
  }
  public void setCity(String city) {
    this.city = city;
  }
  public PostOrderFromSiteDetails place(String place) {
    this.place = place;
    return this;
  }

  

  /**
  * Get place
  * @return place
  **/
  @Schema(description = "")
  public String getPlace() {
    return place;
  }
  public void setPlace(String place) {
    this.place = place;
  }
  public PostOrderFromSiteDetails timeStart(OffsetDateTime timeStart) {
    this.timeStart = timeStart;
    return this;
  }

  

  /**
  * Get timeStart
  * @return timeStart
  **/
  @Schema(description = "")
  public OffsetDateTime getTimeStart() {
    return timeStart;
  }
  public void setTimeStart(OffsetDateTime timeStart) {
    this.timeStart = timeStart;
  }
  public PostOrderFromSiteDetails timeEnd(OffsetDateTime timeEnd) {
    this.timeEnd = timeEnd;
    return this;
  }

  

  /**
  * Get timeEnd
  * @return timeEnd
  **/
  @Schema(description = "")
  public OffsetDateTime getTimeEnd() {
    return timeEnd;
  }
  public void setTimeEnd(OffsetDateTime timeEnd) {
    this.timeEnd = timeEnd;
  }
  public PostOrderFromSiteDetails phone(String phone) {
    this.phone = phone;
    return this;
  }

  

  /**
  * Get phone
  * @return phone
  **/
  @Schema(description = "")
  public String getPhone() {
    return phone;
  }
  public void setPhone(String phone) {
    this.phone = phone;
  }
  public PostOrderFromSiteDetails mailAddress(String mailAddress) {
    this.mailAddress = mailAddress;
    return this;
  }

  

  /**
  * Get mailAddress
  * @return mailAddress
  **/
  @Schema(description = "")
  public String getMailAddress() {
    return mailAddress;
  }
  public void setMailAddress(String mailAddress) {
    this.mailAddress = mailAddress;
  }
  public PostOrderFromSiteDetails attractions(String attractions) {
    this.attractions = attractions;
    return this;
  }

  

  /**
  * Get attractions
  * @return attractions
  **/
  @Schema(description = "")
  public String getAttractions() {
    return attractions;
  }
  public void setAttractions(String attractions) {
    this.attractions = attractions;
  }
  public PostOrderFromSiteDetails comments(String comments) {
    this.comments = comments;
    return this;
  }

  

  /**
  * Get comments
  * @return comments
  **/
  @Schema(description = "")
  public String getComments() {
    return comments;
  }
  public void setComments(String comments) {
    this.comments = comments;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostOrderFromSiteDetails postOrderFromSiteDetails = (PostOrderFromSiteDetails) o;
    return Objects.equals(this.date, postOrderFromSiteDetails.date) &&
        Objects.equals(this.city, postOrderFromSiteDetails.city) &&
        Objects.equals(this.place, postOrderFromSiteDetails.place) &&
        Objects.equals(this.timeStart, postOrderFromSiteDetails.timeStart) &&
        Objects.equals(this.timeEnd, postOrderFromSiteDetails.timeEnd) &&
        Objects.equals(this.phone, postOrderFromSiteDetails.phone) &&
        Objects.equals(this.mailAddress, postOrderFromSiteDetails.mailAddress) &&
        Objects.equals(this.attractions, postOrderFromSiteDetails.attractions) &&
        Objects.equals(this.comments, postOrderFromSiteDetails.comments);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(date, city, place, timeStart, timeEnd, phone, mailAddress, attractions, comments);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostOrderFromSiteDetails {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    place: ").append(toIndentedString(place)).append("\n");
    sb.append("    timeStart: ").append(toIndentedString(timeStart)).append("\n");
    sb.append("    timeEnd: ").append(toIndentedString(timeEnd)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    mailAddress: ").append(toIndentedString(mailAddress)).append("\n");
    sb.append("    attractions: ").append(toIndentedString(attractions)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
