/*
 * HolidayAPI
 * My API work College Work
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import org.threeten.bp.OffsetDateTime;

/**
 * Put Out Details
 */
@Schema(description = "Put Out Details")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2018-11-20T18:36:01.976Z[GMT]")public class PutOutDetails {

  @SerializedName("comments")
  private String comments = null;

  @SerializedName("date")
  private OffsetDateTime date = null;

  @SerializedName("total")
  private BigDecimal total = null;

  @SerializedName("photo")
  private File photo = null;

  @SerializedName("idStatement")
  private Integer idStatement = null;
  public PutOutDetails comments(String comments) {
    this.comments = comments;
    return this;
  }

  

  /**
  * Get comments
  * @return comments
  **/
  @Schema(description = "")
  public String getComments() {
    return comments;
  }
  public void setComments(String comments) {
    this.comments = comments;
  }
  public PutOutDetails date(OffsetDateTime date) {
    this.date = date;
    return this;
  }

  

  /**
  * Get date
  * @return date
  **/
  @Schema(description = "")
  public OffsetDateTime getDate() {
    return date;
  }
  public void setDate(OffsetDateTime date) {
    this.date = date;
  }
  public PutOutDetails total(BigDecimal total) {
    this.total = total;
    return this;
  }

  

  /**
  * Get total
  * @return total
  **/
  @Schema(description = "")
  public BigDecimal getTotal() {
    return total;
  }
  public void setTotal(BigDecimal total) {
    this.total = total;
  }
  public PutOutDetails photo(File photo) {
    this.photo = photo;
    return this;
  }

  

  /**
  * Get photo
  * @return photo
  **/
  @Schema(description = "")
  public File getPhoto() {
    return photo;
  }
  public void setPhoto(File photo) {
    this.photo = photo;
  }
  public PutOutDetails idStatement(Integer idStatement) {
    this.idStatement = idStatement;
    return this;
  }

  

  /**
  * Get idStatement
  * @return idStatement
  **/
  @Schema(description = "")
  public Integer getIdStatement() {
    return idStatement;
  }
  public void setIdStatement(Integer idStatement) {
    this.idStatement = idStatement;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PutOutDetails putOutDetails = (PutOutDetails) o;
    return Objects.equals(this.comments, putOutDetails.comments) &&
        Objects.equals(this.date, putOutDetails.date) &&
        Objects.equals(this.total, putOutDetails.total) &&
        Objects.equals(this.photo, putOutDetails.photo) &&
        Objects.equals(this.idStatement, putOutDetails.idStatement);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(comments, date, total, photo, idStatement);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PutOutDetails {\n");
    
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    photo: ").append(toIndentedString(photo)).append("\n");
    sb.append("    idStatement: ").append(toIndentedString(idStatement)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
