/*
 * HolidayAPI
 * My API work College Work
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ComingDetails;
import io.swagger.client.model.ListOfComings;
import io.swagger.client.model.PostComingDetails;
import io.swagger.client.model.PutComingDetails;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ComingsApi
 */
@Ignore
public class ComingsApiTest {

    private final ComingsApi api = new ComingsApi();

    /**
     * 
     *
     * Delete some coming
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void comingsComingIdDeleteTest() throws ApiException {
        Integer comingId = null;
        api.comingsComingIdDelete(comingId);

        // TODO: test validations
    }
    /**
     * 
     *
     * Reading coming by ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void comingsComingIdGetTest() throws ApiException {
        Integer comingId = null;
        ComingDetails response = api.comingsComingIdGet(comingId);

        // TODO: test validations
    }
    /**
     * 
     *
     * Modify coming
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void comingsComingIdPutTest() throws ApiException {
        Integer comingId = null;
        PutComingDetails body = null;
        api.comingsComingIdPut(comingId, body);

        // TODO: test validations
    }
    /**
     * 
     *
     * Reading list of comings
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void comingsGetTest() throws ApiException {
        ListOfComings response = api.comingsGet();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void comingsPostTest() throws ApiException {
        PostComingDetails body = null;
        api.comingsPost(body);

        // TODO: test validations
    }
}
