/*
 * HolidayAPI
 * My API work College Work
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.EquipmentDetails;
import io.swagger.client.model.ListOfEquipments;
import io.swagger.client.model.PostEquipmentDetails;
import io.swagger.client.model.PutEquipmentDetails;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EquipmentsApi
 */
@Ignore
public class EquipmentsApiTest {

    private final EquipmentsApi api = new EquipmentsApi();

    /**
     * 
     *
     * Read equipment by ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void equipmentEquipmentIdGetTest() throws ApiException {
        Integer equipmentId = null;
        EquipmentDetails response = api.equipmentEquipmentIdGet(equipmentId);

        // TODO: test validations
    }
    /**
     * 
     *
     * Modify equipment by ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void equipmentEquipmentIdPutTest() throws ApiException {
        Integer equipmentId = null;
        PutEquipmentDetails body = null;
        api.equipmentEquipmentIdPut(equipmentId, body);

        // TODO: test validations
    }
    /**
     * 
     *
     * Read equipments
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void equipmentGetTest() throws ApiException {
        ListOfEquipments response = api.equipmentGet();

        // TODO: test validations
    }
    /**
     * 
     *
     * Read equipments by ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void equipmentOrderIdGetTest() throws ApiException {
        Integer orderId = null;
        EquipmentDetails response = api.equipmentOrderIdGet(orderId);

        // TODO: test validations
    }
    /**
     * 
     *
     * Add equipment
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void equipmentPostTest() throws ApiException {
        PostEquipmentDetails body = null;
        api.equipmentPost(body);

        // TODO: test validations
    }
}
