/*
 * HolidayAPI
 * My API work College Work
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ListOfOils;
import io.swagger.client.model.OilDetails;
import io.swagger.client.model.PostOilDetails;
import io.swagger.client.model.PutOilDetails;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OilsApi
 */
@Ignore
public class OilsApiTest {

    private final OilsApi api = new OilsApi();

    /**
     * 
     *
     * Read oils
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void oilsGetTest() throws ApiException {
        ListOfOils response = api.oilsGet();

        // TODO: test validations
    }
    /**
     * 
     *
     * Delete oil by ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void oilsOilIdDeleteTest() throws ApiException {
        Integer oilId = null;
        api.oilsOilIdDelete(oilId);

        // TODO: test validations
    }
    /**
     * 
     *
     * Read oil by ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void oilsOilIdGetTest() throws ApiException {
        Integer oilId = null;
        OilDetails response = api.oilsOilIdGet(oilId);

        // TODO: test validations
    }
    /**
     * 
     *
     * Modify oil by ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void oilsOilIdPutTest() throws ApiException {
        Integer oilId = null;
        PutOilDetails body = null;
        api.oilsOilIdPut(oilId, body);

        // TODO: test validations
    }
    /**
     * 
     *
     * Add oil
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void oilsPostTest() throws ApiException {
        PostOilDetails body = null;
        api.oilsPost(body);

        // TODO: test validations
    }
}
