/*
 * HolidayAPI
 * My API work College Work
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.EquipmentDetails;
import io.swagger.client.model.ListOfOrdersFromSite;
import io.swagger.client.model.OrderFromSiteDetails;
import io.swagger.client.model.PostOrderFromSiteDetails;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrdersApi
 */
@Ignore
public class OrdersApiTest {

    private final OrdersApi api = new OrdersApi();

    /**
     * 
     *
     * Read equipments by ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void equipmentOrderIdGetTest() throws ApiException {
        Integer orderId = null;
        EquipmentDetails response = api.equipmentOrderIdGet(orderId);

        // TODO: test validations
    }
    /**
     * 
     *
     * Read list of Orders From Site
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void orderGetTest() throws ApiException {
        ListOfOrdersFromSite response = api.orderGet();

        // TODO: test validations
    }
    /**
     * 
     *
     * Read order from site by ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void orderOrderIdGetTest() throws ApiException {
        Integer orderId = null;
        OrderFromSiteDetails response = api.orderOrderIdGet(orderId);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void orderPostTest() throws ApiException {
        PostOrderFromSiteDetails body = null;
        api.orderPost(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * Read orders
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void ordersGetTest() throws ApiException {
        api.ordersGet();

        // TODO: test validations
    }
    /**
     * 
     *
     * Read order by ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void ordersOrderIdGetTest() throws ApiException {
        Integer orderId = null;
        api.ordersOrderIdGet(orderId);

        // TODO: test validations
    }
    /**
     * 
     *
     * Read worker by order ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void workersOrderIdGetTest() throws ApiException {
        Integer orderId = null;
        api.workersOrderIdGet(orderId);

        // TODO: test validations
    }
}
