/*
 * HolidayAPI
 * My API work College Work
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.LoginDetails;
import io.swagger.client.model.PostLoginDetails;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SecurityApi
 */
@Ignore
public class SecurityApiTest {

    private final SecurityApi api = new SecurityApi();

    /**
     * 
     *
     * Login
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void loginPostTest() throws ApiException {
        PostLoginDetails body = null;
        LoginDetails response = api.loginPost(body);

        // TODO: test validations
    }
}
