/*
 * HolidayAPI
 * My API work College Work
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ListOfStatements;
import io.swagger.client.model.PostStatementDetails;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StatementsApi
 */
@Ignore
public class StatementsApiTest {

    private final StatementsApi api = new StatementsApi();

    /**
     * 
     *
     * Read statements
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void statementsGetTest() throws ApiException {
        ListOfStatements response = api.statementsGet();

        // TODO: test validations
    }
    /**
     * 
     *
     * Add statement
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void statementsPostTest() throws ApiException {
        PostStatementDetails body = null;
        api.statementsPost(body);

        // TODO: test validations
    }
}
