/*
 * HolidayAPI
 * My API work College Work
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ListOfTasks;
import io.swagger.client.model.PostTaskDetails;
import io.swagger.client.model.PutTaskDetails;
import io.swagger.client.model.TaskDetails;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TasksApi
 */
@Ignore
public class TasksApiTest {

    private final TasksApi api = new TasksApi();

    /**
     * 
     *
     * Read tasks
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void tasksGetTest() throws ApiException {
        ListOfTasks response = api.tasksGet();

        // TODO: test validations
    }
    /**
     * 
     *
     * Add task
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void tasksPostTest() throws ApiException {
        PostTaskDetails body = null;
        api.tasksPost(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * Read task by ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void tasksTaskIdGetTest() throws ApiException {
        Integer taskId = null;
        TaskDetails response = api.tasksTaskIdGet(taskId);

        // TODO: test validations
    }
    /**
     * 
     *
     * Modify task by ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void tasksTaskIdPutTest() throws ApiException {
        Integer taskId = null;
        PutTaskDetails body = null;
        api.tasksTaskIdPut(taskId, body);

        // TODO: test validations
    }
}
