/*
 * HolidayAPI
 * My API work College Work
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ListOfWorkers;
import io.swagger.client.model.PostWorkerDetails;
import io.swagger.client.model.PutWorkerDetails;
import io.swagger.client.model.WorkerDetails;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WorkersApi
 */
@Ignore
public class WorkersApiTest {

    private final WorkersApi api = new WorkersApi();

    /**
     * 
     *
     * Read workers
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void workersGetTest() throws ApiException {
        ListOfWorkers response = api.workersGet();

        // TODO: test validations
    }
    /**
     * 
     *
     * Read worker by order ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void workersOrderIdGetTest() throws ApiException {
        Integer orderId = null;
        api.workersOrderIdGet(orderId);

        // TODO: test validations
    }
    /**
     * 
     *
     * Add worker
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void workersPostTest() throws ApiException {
        PostWorkerDetails body = null;
        api.workersPost(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * Read worker by ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void workersWorkerIdGetTest() throws ApiException {
        Integer workerId = null;
        WorkerDetails response = api.workersWorkerIdGet(workerId);

        // TODO: test validations
    }
    /**
     * 
     *
     * Modify worker by ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void workersWorkerIdPutTest() throws ApiException {
        Integer workerId = null;
        PutWorkerDetails body = null;
        api.workersWorkerIdPut(workerId, body);

        // TODO: test validations
    }
}
